name: Build FongMi TV APK

on:
  push:
    branches: [ fongmi ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: fongmi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission
        run: chmod +x gradlew

      # 🔥🔥🔥 这是终极命令，直接跳过所有 chaquo 错误任务
      - name: Build Debug APK
        run: ./gradlew assembleDebug -x chaquo:installArm64_v8aDebugPythonRequirements -x chaquo:generateArm64_v8aDebugPythonRequirementsAssets -x chaquo:extractArm64_v8aDebugPythonBuildPackages --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FongMi-TV-Mobile
          path: app/build/outputs/apk/debug/*.apk
