name: Build FongMi TV APK

on:
  push:
    branches: [ fongmi ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: fongmi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission
        run: chmod +x gradlew

      # 🔥 只跳过这一个任务，完美解决 Python 错误
      - name: Build Debug APK
        run: ./gradlew assembleDebug -x :chaquo:installArm64_v8aDebugPythonRequirements --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FongMi-TV-Mobile
          path: app/build/outputs/apk/debug/*.apk
